export default [
  {
    name: 'Jon Smith',
    position: 'Software Engineer',
    tags: ['Data Scientist', 'Contractor'],
    bgColor: '#F0B1A4',
    expertise: [
      'Oncology',
      'Machine Learning',
      'Hig Performance Computing',
      'Statistical Modelling',
      'Data Engineering',
      'Genomics',
    ],
    joined: 2019,
    email: '',
    linkedin: '',
    image: '/team/jon.png',
    largeImage: '/team/michael-lg.png',
    description:
      'Michael currently supports oncology programs, manages data transfer and organization, and administrates high performance computing. Before joining Gilead, Biao worked on pharmacogenomics projects at the Buck Institute for Research on Aging and machine learning projects at Indiana University, where he built a popular online tool MutPred for predicting pathogenicity of missense variants. Biao has strong interests in statistics, computing and cancer genomics, and is enthusiastic about some recent advancement in causal inference and numerical optimization. He got a PhD in Bioinformatics in 2006 from the Institute of Biophysics, CAS, China.',
  },
  {
    name: 'Jane Doe',
    position: 'Software Engineer',
    bgColor: '#ECB6FF',
    tags: ['Data Scientist', 'Contractor'],
    description:
      'Michael currently supports oncology programs, manages data transfer and organization, and administrates high performance computing. Before joining Gilead, Biao worked on pharmacogenomics projects at the Buck Institute for Research on Aging and machine learning projects at Indiana University, where he built a popular online tool MutPred for predicting pathogenicity of missense variants. Biao has strong interests in statistics, computing and cancer genomics, and is enthusiastic about some recent advancement in causal inference and numerical optimization. He got a PhD in Bioinformatics in 2006 from the Institute of Biophysics, CAS, China.',
    expertise: [
      'Oncology',
      'Machine Learning',
      'Hig Performance Computing',
      'Statistical Modelling',
      'Data Engineering',
      'Genomics',
    ],
    joined: 2019,
    email: '',
    linkedin: '',
    image: '/team/jane.png',
    largeImage: '/team/jane-lg.png',
  },
  {
    name: ' Ted Green',
    position: 'Software Engineer',
    bgColor: '#ADF1C0',
    tags: ['Data Scientist', 'Contractor'],
    expertise: [
      'Oncology',
      'Machine Learning',
      'Hig Performance Computing',
      'Statistical Modelling',
      'Data Engineering',
      'Genomics',
    ],
    joined: 2019,
    email: '',
    linkedin: '',
    image: '/team/ted.png',
    largeImage: '/team/michael-lg.png',
    description:
      'Michael currently supports oncology programs, manages data transfer and organization, and administrates high performance computing. Before joining Gilead, Biao worked on pharmacogenomics projects at the Buck Institute for Research on Aging and machine learning projects at Indiana University, where he built a popular online tool MutPred for predicting pathogenicity of missense variants. Biao has strong interests in statistics, computing and cancer genomics, and is enthusiastic about some recent advancement in causal inference and numerical optimization. He got a PhD in Bioinformatics in 2006 from the Institute of Biophysics, CAS, China.',
  },
  {
    name: ' James Brown',
    position: 'Software Engineer',
    bgColor: '#A6A4F0',
    tags: ['Data Scientist', 'Contractor'],
    expertise: [
      'Oncology',
      'Machine Learning',
      'Hig Performance Computing',
      'Statistical Modelling',
      'Data Engineering',
      'Genomics',
    ],
    joined: 2019,
    email: '',
    linkedin: '',
    image: '/team/james.png',
    largeImage: '/team/michael-lg.png',
    description:
      'Michael currently supports oncology programs, manages data transfer and organization, and administrates high performance computing. Before joining Gilead, Biao worked on pharmacogenomics projects at the Buck Institute for Research on Aging and machine learning projects at Indiana University, where he built a popular online tool MutPred for predicting pathogenicity of missense variants. Biao has strong interests in statistics, computing and cancer genomics, and is enthusiastic about some recent advancement in causal inference and numerical optimization. He got a PhD in Bioinformatics in 2006 from the Institute of Biophysics, CAS, China.',
  },
  {
    name: ' Michael joe',
    position: 'Software Engineer',
    bgColor: '#FF7A7A',
    tags: ['Data Scientist', 'Contractor'],
    expertise: [
      'Oncology',
      'Machine Learning',
      'Hig Performance Computing',
      'Statistical Modelling',
      'Data Engineering',
      'Genomics',
    ],
    joined: 2019,
    email: '',
    linkedin: '',
    image: '/team/michael.png',
    largeImage: '/team/michael-lg.png',
    description:
      'Michael currently supports oncology programs, manages data transfer and organization, and administrates high performance computing. Before joining Gilead, Biao worked on pharmacogenomics projects at the Buck Institute for Research on Aging and machine learning projects at Indiana University, where he built a popular online tool MutPred for predicting pathogenicity of missense variants. Biao has strong interests in statistics, computing and cancer genomics, and is enthusiastic about some recent advancement in causal inference and numerical optimization. He got a PhD in Bioinformatics in 2006 from the Institute of Biophysics, CAS, China.',
  },
  {
    name: ' Michelle Lee',
    position: 'Software Engineer',
    bgColor: '#8D83FF',
    tags: ['Data Scientist', 'Contractor'],
    expertise: [
      'Oncology',
      'Machine Learning',
      'Hig Performance Computing',
      'Statistical Modelling',
      'Data Engineering',
      'Genomics',
    ],
    joined: 2019,
    email: '',
    linkedin: '',
    image: '/team/mitchelle.png',
    largeImage: '/team/michael-lg.png',
    description:
      'Michael currently supports oncology programs, manages data transfer and organization, and administrates high performance computing. Before joining Gilead, Biao worked on pharmacogenomics projects at the Buck Institute for Research on Aging and machine learning projects at Indiana University, where he built a popular online tool MutPred for predicting pathogenicity of missense variants. Biao has strong interests in statistics, computing and cancer genomics, and is enthusiastic about some recent advancement in causal inference and numerical optimization. He got a PhD in Bioinformatics in 2006 from the Institute of Biophysics, CAS, China.',
  },
]
