export default [
  {
    name: 'Jon Smith',
    position: 'Software Engineer',
    tags: ['Data Scientist', 'Contractor'],
    bgColor: '#F0B1A4',
    expertise: [
      'Oncology',
      'Machine Learning',
      'Hig Performance Computing',
      'Statistical Modelling',
      'Data Engineering',
      'Genomics',
    ],
    joined: 2019,
    email: '',
    linkedin: '',
    image: '/team/jon.png',
  },
  {
    name: ' jane Doe',
    position: 'Software Engineer',
    bgColor: '#ECB6FF',
    tags: ['Data Scientist', 'Contractor'],
    expertise: [
      'Oncology',
      'Machine Learning',
      'Hig Performance Computing',
      'Statistical Modelling',
      'Data Engineering',
      'Genomics',
    ],
    joined: 2019,
    email: '',
    linkedin: '',
    image: '/team/jane.png',
  },
  {
    name: ' Ted Green',
    position: 'Software Engineer',
    bgColor: '#ADF1C0',
    tags: ['Data Scientist', 'Contractor'],
    expertise: [
      'Oncology',
      'Machine Learning',
      'Hig Performance Computing',
      'Statistical Modelling',
      'Data Engineering',
      'Genomics',
    ],
    joined: 2019,
    email: '',
    linkedin: '',
    image: '/team/ted.png',
  },
  {
    name: ' James Brown',
    position: 'Software Engineer',
    bgColor: '#A6A4F0',
    tags: ['Data Scientist', 'Contractor'],
    expertise: [
      'Oncology',
      'Machine Learning',
      'Hig Performance Computing',
      'Statistical Modelling',
      'Data Engineering',
      'Genomics',
    ],
    joined: 2019,
    email: '',
    linkedin: '',
    image: '/team/james.png',
  },
  {
    name: ' Michael joe',
    position: 'Software Engineer',
    bgColor: '#FF7A7A',
    tags: ['Data Scientist', 'Contractor'],
    expertise: [
      'Oncology',
      'Machine Learning',
      'Hig Performance Computing',
      'Statistical Modelling',
      'Data Engineering',
      'Genomics',
    ],
    joined: 2019,
    email: '',
    linkedin: '',
    image: '/team/michael.png',
  },
  {
    name: ' Michelle Lee',
    position: 'Software Engineer',
    bgColor: '#8D83FF',
    tags: ['Data Scientist', 'Contractor'],
    expertise: [
      'Oncology',
      'Machine Learning',
      'Hig Performance Computing',
      'Statistical Modelling',
      'Data Engineering',
      'Genomics',
    ],
    joined: 2019,
    email: '',
    linkedin: '',
    image: '/team/mitchelle.png',
  },
]
