<template>
  <div
    class="relative w-full h-[500px] flex flex-col justify-around pl-12 2xl:pl-[13rem] pt-6"
  >
    <h4
      class="font-light tracking-tighter text-3xl 2xl:text-5xl text-gray-900 mt-4"
    >
      <span class="text-2xl lg:text-5xl 2xl:text-7xl font-light">
        Welcome, <span class="text-red-700">John</span></span
      >
      <br />
      to Bioinformatics Data Hub
    </h4>

    <p class="text-base pb-12 text-gray-800 text-sm w-[500px]">
      This website serves as a data hub for molecular data collected from either
      Gilead sponsored clinical trials or data generated by public consortia. We
      also provide user-friendly data analysis and visualization tools to foster
      cross-functional data sharing. This site is hosted by Gilead's clinical
      bioinformatics department.
    </p>

    <div class="h-20"></div>
    <div
      class="absolute right-0 w-3/4 rounded-3xl bg-[#C51F3F1A] bg-opacity-10 h-[500px] 2xl:h-[650px] 2xl:mt-20"
    >
      <div class="relative ml-40 pt-10">
        <div class="absolute -ml-40 2xl:ml-[8rem] left-[6rem] top-10">
          <svg
            width="54"
            height="54"
            viewBox="0 0 54 54"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M53.3165 53.6284C23.8706 53.6284 -1.04342e-06 29.7577 -2.33054e-06 0.31189L53.3165 0.311887L53.3165 53.6284Z"
              fill="#C51F3F"
              fill-opacity="0.3"
            />
          </svg>
          <img
            src="~/static/home-glove-vial.png"
            class="-mt-20 transform 2xl:hidden h-[440px] w-[376px] object-contain ml-[8rem]"
          />
        </div>

        <div
          class="absolute -ml-36 left-20 -bottom-[1rem] 2xl:bottom-[6.5rem] 2xl:-ml-0"
        >
          <svg
            width="59"
            height="35"
            viewBox="0 0 59 35"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M0.16684 34.3604L0.166839 29.2826C0.166839 13.1575 13.2388 0.0855097 29.364 0.085509C45.4891 0.0855083 58.5611 13.1575 58.5611 29.2826L58.5611 34.3604L0.16684 34.3604Z"
              fill="#C51F3F"
            />
          </svg>
        </div>

        <!--              <img src="~/static/Rectangle 51.svg" class=" w-72 2xl:w-[36rem] 2xl:relative 2xl:ml-[20%]" />-->
        <svg
          class="w-84 2xl:w-[36rem] 2xl:relative 2xl:ml-[20%]"
          width="338"
          height="349"
          viewBox="0 0 338 349"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M0.127792 0.312805H172.97C264.002 0.312805 337.799 74.1093 337.799 165.142V183.31C337.799 274.343 264.002 348.139 172.97 348.139H164.957C73.9243 348.139 0.127792 274.343 0.127792 183.31V0.312805Z"
            fill="#9494FF"
            fill-opacity="0.5"
          />
        </svg>

        <div
          class="absolute h-[800px] rounded-b-full rounded-t-xl top-32 z-40 right-0 pr-2 bg-[#FEEFEF] w-[500px] 2xl:w-[514px] 2xl:right-[7.5rem]"
        >
          <img
            src="~/static/home-glove-vial.png"
            class="absolute -left-[30rem] hidden 2xl:block -mt-[7rem] transform -z-10 h-[440px] w-[376px] 2xl:w-[740px] 2xl:h-[570px] object-contain ml-[4rem]"
          />

          <div class="absolute -top-14 -left-28 w-40">
            <img src="~/static/message.svg" />
          </div>
          <div class="content p-4">
            <h1 class="font-bold text-xl mb-2 text-gray-600">Quick Links</h1>
            <div class="w-full">
              <hero-card
                v-for="(feature, index) in features"
                :key="index"
                :item="feature"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import HeroCard from './HeroCard.vue'
export default {
  components: { HeroCard },
  name: 'IndexHero',
  data() {
    return {
      features: [
        {
          name: 'Clinical Trial Data Analysis',
          description:
            'Using data from our clinical trials, you can explore demographics, analyze gene expressions, inspect biomarker correlations, and much more.',
          src: require('~/static/link1.svg'),
          href: '/custom-plot',
        },
        {
          name: 'COVID-19 Publication Search',
          description:
            'Utilize advanced ML methods to search a large database of 200,000+ COVID-19 related publications for specific insights.',
          src: require('~/static/link2.svg'),
          href: '#',
        },
        {
          name: 'CommonKnowledge',
          description: 'Lorem Ipsum...',
          src: require('~/static/icon-common-knowledge.svg'),
          href: '#',
        },
        {
          name: 'Tableau Dashboards',
          description: 'Lorem Ipsum...',
          src: require('~/static/icon-tableau.svg'),
          href: '#',
        },
        {
          name: 'Additional Resources',
          description: 'You can find links to other useful resources for molecular data analysis, such as cBioPortal and our Single Cell Visualizer platform.',
          src: require('~/static/icon-additional-resources.svg'),
          href: '#',
        },
      ],
    }
  },
}
</script>
